### PR TITLE
Implemented CanReadTypeCore()

### PR DESCRIPTION
**Pull request by bastianeicher**
Determine serializability by looking for ProtoContractAttribute

### CODE REVIEW

**Comment by filipw** [comment]
thanks

**Comment by bacobart** [comment]
Shouldn't you also check for DataContractAttribute?

**Comment by filipw** [comment]
no it's not mandatory

**Comment by bacobart** [comment]
why not? before classes decorated with DataContract instead of ProtoContract could also be serialized with protobuf, now they are not supported anymore?

**Comment by bastianeicher** [comment]
I think this is just a small misunderstanding.

@bacobart I believe you are suggesting `CanReadTypeCore()` should return `true` if `DataContract` *or* `ProtoContract` is present. Sounds like a good idea, I simply forgot about `DataContract` in my pull request.

@filipw I believe you understood @bacobart to be suggesting checking if `DataContract` *and* `ProtoContract` are present.

**Pull request merged**
